### ISSUE TITLE
"New validator registered" but not in "sk-val validator ls"

### ISSUE THREAD

**Issue by gaia** [skalenetwork/validator-cli#85]
```
sk-val validator register -n FreshSKALE -d "Skale Fuji Testnet" -c 20 --min-delegation 1000 --pk-file ./pk.txt
Are you sure you want to register a new validator account?
Please, re-check all values above before confirming. [y/N]: y
✔ New validator registered
```

![image](https://user-images.githubusercontent.com/87547/82286521-c3d36300-9952-11ea-985d-79fbbae819d0.png)

Registered 0xaCaF87A99d8056D5a2E8dAf1a9754301319f2d2e

**Comment by cstrangedk** [comment]
New validators can either be trusted or not.

`sk-val validator ls` returns only trusted validators.  Try `sk-val validator ls --all`

See https://github.com/skalenetwork/validator-cli/blob/a2370b08f5845d7ce3ff65737b428a656c9118a3/core/validator.py#L47
